# Generated by Django 5.2.4 on 2025-07-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'position')},
        ),
    ]
