# Generated by Django 5.2.4 on 2025-07-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_candidate_position_ballot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.position'),
            preserve_default=False,
        ),
    ]
