# Generated by Django 5.2.4 on 2025-07-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_candidate_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('employee', 'position')},
        ),
    ]
