# Generated by Django 5.2.4 on 2025-07-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ballot_options_alter_ballot_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballot',
            options={},
        ),
    ]
