# Generated by Django 5.2.4 on 2025-07-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ballot_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together=set(),
        ),
    ]
