# Generated by Django 5.2.4 on 2025-07-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ballot_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballot',
            options={'verbose_name_plural': 'Ballots'},
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('candidate', 'position', 'election')},
        ),
    ]
