# Generated by Django 5.2.4 on 2025-07-22 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_vote_unique_together_vote_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('voter', 'election'), include=('ballot',), name='unique_vote_per_position_per_election'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='position',
        ),
    ]
