# Generated by Django 5.2.4 on 2025-07-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_position_per_election',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'ballot')},
        ),
    ]
