# Generated by Django 5.2.4 on 2025-07-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_vote_unique_together_vote_position_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'position', 'ballot')},
        ),
    ]
