# Generated by Django 5.2.4 on 2025-07-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'position')},
        ),
    ]
